FROM node:alpine as basebuilder
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

#/app/build -> basebuilder
FROM nginx
COPY --from=basebuilder /app/build /usr/share/nginx/html/