sudo: required
services:
    - docker

before_install:
    - docker build -t travisci-image -f ./frontend/dockerfile.dev ./frontend/.

script:
    - docker run travisci-image npm run test -- --coverage